"""
ascend Feature 6 — Autonomous Incident Reporter
═══════════════════════════════════════════════════
Generates formal incident reports for high-risk emails
(risk > configurable threshold, default 80).

Report includes:
  • Executive Summary
  • Evidence catalogue
  • Intent classification with ontology chains
  • Mitigation recommendations
  • Export as formatted text

Boundary: Passive only — never auto-sends reports.
User must explicitly request generation and export.
"""

from datetime import datetime, timezone
from ascend import ascend_config


def should_generate_report(risk_score: float) -> bool:
    """Check if risk score exceeds the incident threshold."""
    if not ascend_config.INCIDENT_REPORTER_ENABLED:
        return False
    return risk_score >= ascend_config.INCIDENT_THRESHOLD


def generate_incident_report(
    email_meta: dict,
    risk_score: float,
    risk_level: str,
    intent: str,
    findings: list[dict],
    ontology_data: list[dict] = None,
    summary: str = "",
) -> dict:
    """
    Generate a formal incident report.

    Args:
        email_meta:    Dict with id, subject, sender, date.
        risk_score:    Final risk score from core engine.
        risk_level:    "Low" | "Medium" | "High".
        intent:        Classified phishing intent.
        findings:      List of finding dicts.
        ontology_data: Optional ontology chains from Feature 2.
        summary:       Explanation summary from core engine.

    Returns:
        Structured incident report dict.
    """
    if not ascend_config.INCIDENT_REPORTER_ENABLED:
        return {}

    report_id = f"IR-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}"
    timestamp = datetime.now(timezone.utc).isoformat()

    # ── Evidence catalogue ──
    evidence_items = []
    for f in findings:
        evidence_items.append({
            "category": f.get("analyzer", "unknown"),
            "indicator": f.get("indicator", ""),
            "description": f.get("explanation", ""),
            "evidence": f.get("evidence", ""),
            "severity_contribution": f.get("score", 0),
        })

    # ── Threat chains from ontology ──
    threat_chains = []
    if ontology_data:
        for entry in ontology_data:
            for chain in entry.get("chains", []):
                threat_chains.append({
                    "evidence": entry.get("evidence", ""),
                    "intent": chain.get("intent", ""),
                    "impact": chain.get("impact", ""),
                })

    # ── Mitigation recommendations ──
    mitigations = _generate_mitigations(intent, findings)

    # ── Executive summary ──
    exec_summary = (
        f"A phishing email with a risk score of {risk_score:.0f}/100 "
        f"({risk_level} severity) was detected. The primary intent is "
        f"classified as '{intent}'. {len(findings)} suspicious indicators "
        f"were identified across {len(set(f.get('analyzer', '') for f in findings))} "
        f"analysis categories. Immediate user awareness and caution is recommended."
    )

    return {
        "report_id": report_id,
        "timestamp": timestamp,
        "classification": "PHISHING INCIDENT",
        "severity": risk_level,
        "risk_score": risk_score,
        "executive_summary": exec_summary,
        "email": {
            "message_id": email_meta.get("id", ""),
            "subject": email_meta.get("subject", ""),
            "sender": email_meta.get("sender", ""),
            "date": email_meta.get("date", ""),
        },
        "intent": intent,
        "engine_summary": summary,
        "evidence": evidence_items,
        "threat_chains": threat_chains,
        "mitigations": mitigations,
        "status": "GENERATED — Pending Review",
        "disclaimer": (
            "This report was automatically generated by PhishGuard ascend. "
            "It is advisory in nature and should be reviewed by a security "
            "professional before any action is taken."
        ),
    }


def export_as_text(report: dict) -> str:
    """
    Export incident report as formatted plain text.
    Suitable for copy-paste into PDF or formal documentation.
    """
    if not report:
        return ""

    lines = []
    lines.append("=" * 72)
    lines.append(f"  PHISHING INCIDENT REPORT — {report.get('report_id', 'N/A')}")
    lines.append("=" * 72)
    lines.append("")
    lines.append(f"  Generated:      {report.get('timestamp', '')}")
    lines.append(f"  Classification: {report.get('classification', '')}")
    lines.append(f"  Severity:       {report.get('severity', '')} ({report.get('risk_score', 0):.0f}/100)")
    lines.append(f"  Status:         {report.get('status', '')}")
    lines.append("")

    # Executive Summary
    lines.append("-" * 72)
    lines.append("  EXECUTIVE SUMMARY")
    lines.append("-" * 72)
    lines.append(f"  {report.get('executive_summary', '')}")
    lines.append("")

    # Email Details
    email = report.get("email", {})
    lines.append("-" * 72)
    lines.append("  EMAIL DETAILS")
    lines.append("-" * 72)
    lines.append(f"  Message ID: {email.get('message_id', '')}")
    lines.append(f"  Subject:    {email.get('subject', '')}")
    lines.append(f"  Sender:     {email.get('sender', '')}")
    lines.append(f"  Date:       {email.get('date', '')}")
    lines.append("")

    # Intent
    lines.append(f"  Classified Intent: {report.get('intent', '')}")
    lines.append(f"  Engine Summary:    {report.get('engine_summary', '')}")
    lines.append("")

    # Evidence
    evidence = report.get("evidence", [])
    lines.append("-" * 72)
    lines.append(f"  EVIDENCE ({len(evidence)} indicators)")
    lines.append("-" * 72)
    for i, e in enumerate(evidence, 1):
        lines.append(f"  {i}. [{e.get('category', '')}] {e.get('indicator', '')}")
        lines.append(f"     Severity: +{e.get('severity_contribution', 0):.1f} pts")
        lines.append(f"     Evidence: {e.get('evidence', '')}")
        lines.append(f"     Detail:   {e.get('description', '')}")
        lines.append("")

    # Threat Chains
    chains = report.get("threat_chains", [])
    if chains:
        lines.append("-" * 72)
        lines.append(f"  THREAT CHAINS ({len(chains)} identified)")
        lines.append("-" * 72)
        for c in chains:
            lines.append(
                f"  {c.get('evidence', '')} → {c.get('intent', '')} → {c.get('impact', '')}"
            )
        lines.append("")

    # Mitigations
    mitigations = report.get("mitigations", [])
    lines.append("-" * 72)
    lines.append("  RECOMMENDED MITIGATIONS")
    lines.append("-" * 72)
    for m in mitigations:
        lines.append(f"  • {m}")
    lines.append("")

    # Disclaimer
    lines.append("-" * 72)
    lines.append(f"  DISCLAIMER: {report.get('disclaimer', '')}")
    lines.append("=" * 72)

    return "\n".join(lines)


def _generate_mitigations(intent: str, findings: list[dict]) -> list[str]:
    """Generate context-aware mitigation recommendations."""
    mitigations = [
        "Do NOT click any links or download attachments from this email.",
        "Do NOT reply to this email or provide any personal information.",
    ]

    indicators = set(f.get("indicator", "") for f in findings)

    if intent == "Credential Harvesting":
        mitigations.append(
            "If you entered credentials on a linked page, immediately change your "
            "password and enable two-factor authentication (2FA)."
        )

    if intent == "Financial Fraud":
        mitigations.append(
            "If you shared financial information, contact your bank immediately "
            "and monitor your accounts for unauthorized transactions."
        )

    if intent == "Malware Delivery":
        mitigations.append(
            "If you downloaded any attachments, run a full antivirus scan "
            "immediately and consider disconnecting from the network."
        )

    if intent == "Identity Theft":
        mitigations.append(
            "If you shared personal identification information, consider placing "
            "a fraud alert or credit freeze with major credit bureaus."
        )

    if "shortened_url" in indicators or "ip_based_url" in indicators:
        mitigations.append(
            "Report suspicious URLs to Google Safe Browsing (safebrowsing.google.com) "
            "and your organization's security team."
        )

    mitigations.extend([
        "Report this email as phishing in your email client.",
        "Alert your IT security team or administrator about this incident.",
        "Warn colleagues who may have received similar emails.",
    ])

    return mitigations
